// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Referralcode.Data;

#nullable disable

namespace Referralcode.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525063449_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Referralcode.Models.ReferralApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxReferrals")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinReferrals")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtherTargetAudience")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RewardPoints")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetAudiences")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReferralApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
